import fs from 'fs-extra';
import * as path from 'path';
import { execSync } from 'child_process';
import { logger } from './logger.js';
import { getComponent, readComponentFile, readTokenFile } from './registry.js';
import { getConfig } from './config.js';

/**
 * Add a component to the consumer's project.
 *
 * 1. Copies component source files into <componentsDir>/<name>/
 * 2. Installs npm dependencies (e.g. @radix-ui/react-slot)
 * 3. Creates the design tokens CSS file if it doesn't exist yet
 */
export async function addComponent(name: string, cwd: string): Promise<void> {
  const component = await getComponent(name);

  if (!component) {
    logger.error(`Component "${name}" not found in registry.`);
    logger.dim(`  Run \`sparks-ds list\` to see available components.`);
    process.exit(1);
  }

  const config = await getConfig(cwd);

  // ── 1. Copy component files ───────────────────────────────────────────────
  const targetDir = path.join(cwd, config.componentsDir, name);
  await fs.ensureDir(targetDir);

  logger.step(`Copying files to ${path.relative(cwd, targetDir)}/`);

  for (const file of component.files) {
    const content    = await readComponentFile(name, file);
    const targetPath = path.join(targetDir, file);
    const existed    = await fs.pathExists(targetPath);

    await fs.writeFile(targetPath, content, 'utf-8');
    logger.step(`${existed ? 'Overwrote' : 'Copied  '} ${file}`);
  }

  // ── 2. Install npm dependencies ───────────────────────────────────────────
  if (component.dependencies.length > 0) {
    logger.step(`Installing: ${component.dependencies.join(', ')}`);

    try {
      // Detect package manager from lock file
      const pm = detectPackageManager(cwd);
      const cmd = buildInstallCommand(pm, component.dependencies);

      execSync(cmd, { cwd, stdio: 'inherit' });
    } catch {
      logger.warn('Automatic install failed. Add these dependencies manually:');
      logger.dim(`  npm install ${component.dependencies.join(' ')}`);
    }
  }

  // ── 3. Ensure design tokens file exists ───────────────────────────────────
  const tokensPath = path.join(cwd, config.tokensFile);

  if (!(await fs.pathExists(tokensPath))) {
    logger.step(`Creating ${config.tokensFile}`);
    await fs.ensureDir(path.dirname(tokensPath));

    const parts: string[] = [
      `/* Sparks Design System — Design Tokens`,
      ` * Auto-generated by \`sparks-ds add ${name}\`.`,
      ` * Import this file once in your app entry (e.g. main.tsx or _app.tsx):`,
      ` *   import './styles/tokens.css'`,
      ` */`,
      ``,
    ];

    for (const tokenFile of component.tokens) {
      parts.push(await readTokenFile(tokenFile));
      parts.push('');
    }

    await fs.writeFile(tokensPath, parts.join('\n').trimEnd() + '\n', 'utf-8');
    logger.step(`Created ${config.tokensFile} — import it in your app entry point`);
  } else {
    logger.dim(`  ${config.tokensFile} already exists — skipped`);
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

type PackageManager = 'npm' | 'pnpm' | 'yarn' | 'bun';

function detectPackageManager(cwd: string): PackageManager {
  if (fs.existsSync(path.join(cwd, 'bun.lockb')))        return 'bun';
  if (fs.existsSync(path.join(cwd, 'pnpm-lock.yaml')))   return 'pnpm';
  if (fs.existsSync(path.join(cwd, 'yarn.lock')))        return 'yarn';
  return 'npm';
}

function buildInstallCommand(pm: PackageManager, deps: string[]): string {
  const pkgs = deps.join(' ');
  switch (pm) {
    case 'pnpm': return `pnpm add ${pkgs}`;
    case 'yarn': return `yarn add ${pkgs}`;
    case 'bun':  return `bun add ${pkgs}`;
    default:     return `npm install ${pkgs}`;
  }
}
